### ISSUE TITLE
Unable to load the mod for forge 1.12.2

### ISSUE THREAD

**Issue by Edouard127** [3arthqu4ke/HMC-Specifics#1]
```
[03:04:01] [Client thread/ERROR] [FML]: There was a problem reading the entry module-info.class in the jar /headlessmc/headlessmc-scripts/HeadlessMC/47af666c-cbc0-421c-b826-f80b79182695/headlessmc-lwjgl.jar - probably a corrupt zip
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException

        at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:63) ~[ASMModParser.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.findClassesASM(JarDiscoverer.java:102) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:77) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
        at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
        at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
        at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:425) [Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566) [Loader.class:?]
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
        at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:57) ~[ASMModParser.class:?]
        ... 17 more
[03:04:01] [Client thread/WARN] [FML]: Zip file headlessmc-lwjgl.jar failed to read properly, it will be ignored
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException

        at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:63) ~[ASMModParser.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.findClassesASM(JarDiscoverer.java:102) ~[JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:77) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
        at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
        at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
        at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:425) [Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566) [Loader.class:?]
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
        at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:57) ~[ASMModParser.class:?]
        ... 17 more
```

**Comment by Edouard127** [comment]
I assume my forge version is not the same as the mod

**Comment by 3arthqu4ke** [comment]
No, it is because the jar the HeadlessMc-Launcher uses to remove the rendering contains a class which is java 9. BUT, this does not crash you, right? From my observations it should not matter.

**Comment by 3arthqu4ke** [comment]
You are not putting the headlessmc-lwjgl.jar in your mods folder manually? That is only meant in case you want to launch headlessly with other launchers.

**Comment by Edouard127** [comment]
I thought it was to use the commands such as
- gui
- click

Because I don't have those

**Comment by 3arthqu4ke** [comment]
The hmc-specifics jar (https://github.com/3arthqu4ke/HMC-Specifics/releases) yes, the lwjgl.jar no.

**Comment by 3arthqu4ke** [comment]
You should have those commands if you place the 1.12.2-b2 hmc-specifics jar in your mod folder. The Excpetion from this issue might occur but it wont stop anything from working.

**Comment by Edouard127** [comment]
I had the hmc specifics 1.12.2 b2 full mod in my mods folder

The issues happened when I placed it in

**Comment by 3arthqu4ke** [comment]
Yeh but the game should resume and after some time gui and click commands should be available?

**Comment by Edouard127** [comment]
![image](https://user-images.githubusercontent.com/46357922/182926091-e38df32e-5de0-44d0-8c91-a06a7f47e51f.png)
There's not a lot going on when I try to enter commands

**Comment by Edouard127** [comment]
My bad I had to launch with `-commands`

But I don't see the commands to control the game

**Comment by 3arthqu4ke** [comment]
You do not need to launch with `-commands` when using the HMC-Specifics. `-commands` adds a build-in system which is not as powerful as the HMC-Specifics. 
Idk why nothing is happening when you enter a command. Maybe press enter another time?

**Comment by Edouard127** [comment]
![image](https://user-images.githubusercontent.com/46357922/182940294-73650c73-1b8c-41b1-80c9-d743feb1add4.png)
Still nothing

**Comment by 3arthqu4ke** [comment]
Are you using other mods than HeadlessMc? Is this on the docker image?

**Comment by Edouard127** [comment]
Yes, let me test with only this mod

**Comment by Edouard127** [comment]
Same thing with no mods

**Comment by 3arthqu4ke** [comment]
What does the command look like that you use to launch Minecraft with HeadlessMc?

**Comment by Edouard127** [comment]
Can you elaborate on what you meant ?

**Comment by Edouard127** [comment]
My bad, got it
`hmc launch 1.12.2-forge1.12.2-14.23.5.2815`

**Comment by 3arthqu4ke** [comment]
Can you do `hmc forge 1.12.2`? That should install the latest, forge-14.23.5.2860. Can you try it with that one?

Also if you list versions via `hmc versions` there's also a column called id, you can do `hmc launch <id> -id` that way you do not need to type in the full name.

**Comment by Edouard127** [comment]
Same thing with the latest forge

**Comment by 3arthqu4ke** [comment]
Is it possible that you send the full log? Check that it does not contain any personal info.

**Comment by 3arthqu4ke** [comment]
Or do you see anything like this in the log:
`[java.lang.ThreadGroup:uncaughtException:1052]: java.io.IOError: java.io.IOException: Bad file descriptor`?

**Comment by Edouard127** [comment]
No I don't see this error

**Comment by Edouard127** [comment]
> Is it possible that you send the full log? Check that it does not contain any personal info.

```
Launching version 1.12.2-forge-14.23.5.2860, adc37eb9-7f9c-49cb-8ecc-476e20227e94
[23:46:32] [main/INFO] [ProcessFactory]: Game will run in /headlessmc/headlessmc-scripts/HeadlessMC/run
[23:46:35] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:46:35] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:46:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:46:35] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[23:46:35] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_332, running on Linux:amd64:5.10.102.1-microsoft-standard-WSL2, installed at /usr/local/openjdk-8/jre
[23:46:36] [main/ERROR] [FML]: Unable to read the jar file HMC-Specifics-1.12.2-b1-full.jar - ignoring
java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_332]
        at java.util.zip.ZipFile.<init>(ZipFile.java:228) ~[?:1.8.0_332]
        at java.util.zip.ZipFile.<init>(ZipFile.java:157) ~[?:1.8.0_332]
        at java.util.jar.JarFile.<init>(JarFile.java:171) ~[?:1.8.0_332]
        at java.util.jar.JarFile.<init>(JarFile.java:135) ~[?:1.8.0_332]
        at net.minecraftforge.fml.relauncher.libraries.LibraryManager.extractPacked(LibraryManager.java:200) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.libraries.LibraryManager.cleanDirectory(LibraryManager.java:169) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.libraries.LibraryManager.setup(LibraryManager.java:97) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:106) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[23:46:36] [main/INFO] [FML]: Searching /headlessmc/headlessmc-scripts/HeadlessMC/run/mods for mods
[23:46:36] [main/ERROR] [FML]: Unable to read the jar file HMC-Specifics-1.12.2-b1-full.jar - ignoring
java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_332]
        at java.util.zip.ZipFile.<init>(ZipFile.java:228) ~[?:1.8.0_332]
        at java.util.zip.ZipFile.<init>(ZipFile.java:157) ~[?:1.8.0_332]
        at java.util.jar.JarFile.<init>(JarFile.java:171) ~[?:1.8.0_332]
        at java.util.jar.JarFile.<init>(JarFile.java:135) ~[?:1.8.0_332]
        at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:366) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[23:46:36] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:46:36] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:46:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:46:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:46:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:46:41] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[23:46:41] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[23:46:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:46:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:46:42] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:46:42] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:46:42] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[23:46:43] [Client thread/INFO] [minecraft/Minecraft]: Setting user: ***
[23:46:51] [Client thread/INFO] [minecraft/Minecraft]: LWJGL Version: HeadlessMc-Lwjgl
[23:46:52] [Client thread/INFO] [FML]: -- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Linux (amd64) version 5.10.102.1-microsoft-standard-WSL2
        Java Version: 1.8.0_332, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 688470312 bytes (656 MB) / 869793792 bytes (829 MB) up to 2213019648 bytes (2110 MB)
        JVM Flags: 0 total;
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML:
        Loaded coremods (and transformers):
        GL info: ' Vendor: '' Version: '' Renderer: ''
[23:46:52] [Client thread/INFO] [FML]: MinecraftForge v14.23.5.2860 Initialized
[23:46:52] [Client thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[23:46:52] [Client thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[23:46:52] [Client thread/INFO] [FML]: Replaced 1227 ore ingredients
[23:46:53] [Client thread/INFO] [FML]: Searching /headlessmc/headlessmc-scripts/HeadlessMC/run/mods for mods
[23:46:54] [Thread-2/INFO] [FML]: Using alternative sync timing : 200 frames of Display.update took 2169450000 nanos
[23:46:55] [Client thread/ERROR] [FML]: Unable to read a class file correctly
java.lang.IllegalArgumentException: null
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
        at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:57) [ASMModParser.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.findClassesASM(JarDiscoverer.java:102) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:77) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
        at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
        at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
        at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:427) [Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) [Loader.class:?]
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[23:46:55] [Client thread/ERROR] [FML]: There was a problem reading the entry module-info.class in the jar /headlessmc/headlessmc-scripts/HeadlessMC/adc37eb9-7f9c-49cb-8ecc-476e20227e94/headlessmc-lwjgl.jar - probably a corrupt zip
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException

        at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:63) ~[ASMModParser.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.findClassesASM(JarDiscoverer.java:102) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:77) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
        at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
        at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
        at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:427) [Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) [Loader.class:?]
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
        at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:57) ~[ASMModParser.class:?]
        ... 17 more
[23:46:55] [Client thread/WARN] [FML]: Zip file headlessmc-lwjgl.jar failed to read properly, it will be ignored
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException

        at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:63) ~[ASMModParser.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.findClassesASM(JarDiscoverer.java:102) ~[JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:77) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
        at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
        at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
        at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:427) [Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) [Loader.class:?]
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
        at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:57) ~[ASMModParser.class:?]
        ... 17 more
[23:46:55] [Client thread/WARN] [FML]: Zip file HMC-Specifics-1.12.2-b1-full.jar failed to read properly, it will be ignored
java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_332]
        at java.util.zip.ZipFile.<init>(ZipFile.java:228) ~[?:1.8.0_332]
        at java.util.zip.ZipFile.<init>(ZipFile.java:157) ~[?:1.8.0_332]
        at java.util.jar.JarFile.<init>(JarFile.java:171) ~[?:1.8.0_332]
        at java.util.jar.JarFile.<init>(JarFile.java:135) ~[?:1.8.0_332]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:56) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
        at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
        at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
        at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:427) [Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) [Loader.class:?]
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[23:46:55] [Client thread/INFO] [FML]: Forge Mod Loader has identified 4 mods to load
[23:46:55] [Client thread/INFO] [FML]: FML has found a non-mod file HMC-Specifics-1.12.2-b1-full.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[23:46:55] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge] at CLIENT
[23:46:55] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge] at SERVER
[23:46:56] [Client thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[23:46:57] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[23:46:57] [Client thread/INFO] [FML]: Found 1168 ObjectHolder annotations
[23:46:57] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[23:46:57] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[23:46:57] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[23:46:57] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[23:46:57] [Client thread/INFO] [FML]: Applying holder lookups
[23:46:57] [Client thread/INFO] [FML]: Holder lookups applied
[23:46:57] [Client thread/INFO] [FML]: Applying holder lookups
[23:46:57] [Client thread/INFO] [FML]: Holder lookups applied
[23:46:57] [Client thread/INFO] [FML]: Applying holder lookups
[23:46:57] [Client thread/INFO] [FML]: Holder lookups applied
[23:46:57] [Client thread/INFO] [FML]: Applying holder lookups
[23:46:57] [Client thread/INFO] [FML]: Holder lookups applied
[23:46:57] [Client thread/INFO] [FML]: Injecting itemstacks
[23:46:57] [Client thread/INFO] [FML]: Itemstack injection complete
[23:46:58] [Sound Library Loader/INFO] [minecraft/SoundManager]: Starting up SoundSystem...
[23:46:58] [Thread-3/INFO] [minecraft/SoundManager]: Initializing
[23:46:58] [Thread-3/INFO] [minecraft/SoundManager]: ()
[23:46:59] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: AHEAD Target: null
[23:46:59] [Sound Library Loader/INFO] [minecraft/SoundManager]: Sound engine started
[23:47:02] [Client thread/INFO] [FML]: Max texture size: 16384
[23:47:04] [Client thread/INFO] [minecraft/TextureMap]: Created: 512x512 textures-atlas
[23:47:08] [Client thread/INFO] [FML]: Applying holder lookups
[23:47:08] [Client thread/INFO] [FML]: Holder lookups applied
[23:47:08] [Client thread/INFO] [FML]: Injecting itemstacks
[23:47:08] [Client thread/INFO] [FML]: Itemstack injection complete
[23:47:09] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 4 mods
[23:47:09] [Client thread/INFO] [mojang/NarratorLinux]: Narrator library successfully loaded
```

**Comment by Edouard127** [comment]
For some reason the jar file is empty

**Comment by Edouard127** [comment]
Oh, I feel dumb, I curled the release with -O instead of -LO

Issue fixed
