### ISSUE TITLE
1.8.9 and 1.12.2 mod doesnt load just gives error message

### ISSUE THREAD

**Issue by Makergear25** [3arthqu4ke/hmc-specifics#10]
I headlessmc terminal it says

"There was a problem reading the entry me/earth/headlessmc/specifics/mixins/MixinButton.class in the jar C:\Users\Noah stollman\AppData\Roaming\.minecraft\mods\hmc-specifics-forge-1.20.4-1.8.1.jar - probably a corrupt zip
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException

        at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:63) ~[ASMModParser.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.findClassesASM(JarDiscoverer.java:102) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:77) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
        at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
        at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
        at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:427) [Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) [Loader.class:?]
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
        at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:57) ~[ASMModParser.class:?]
        ... 17 more"

and the mod does load

**Comment by 3arthqu4ke** [comment]
`probably a corrupt zip`, just redownload
